const ADD_POST = 'ADD_POST';
const EDIT_POST = 'EDIT_POST';
const DELETE_POST = 'DELETE_POST';
const ADD_COMMENT = 'ADD_COMMENT'
const DELETE_COMMENT = 'DELETE_COMMENT';
const UPVOTE_POST = 'UPVOTE_POST';
const DOWNVOTE_POST = 'DOWNVOTE_POST'

export { ADD_POST, ADD_COMMENT, DELETE_COMMENT, UPVOTE_POST, DOWNVOTE_POST, DELETE_POST, EDIT_POST }