const ADD_POST = 'ADD_POST';
const DELETE_POST = 'DELETE_POST';
const ADD_COMMENT = 'ADD_COMMENT'
const DELETE_COMMENT = 'DELETE_COMMENT';
const SHOW_ERROR = 'SHOW_ERROR';
const SHOW_POST = 'SHOW_POST';
const GET_POSTS = 'GET_POSTS';
const GET_POST = 'GET_POST';
const CLEAR_POST = 'CLEAR_POST';
const SHOW_LOADING = 'SHOW_LOADING';
const UPDATE_POST = 'UPDATE_POST';
const CLEAR_ERRORS = 'CLEAR_ERRORS';

export {
  ADD_POST, ADD_COMMENT, DELETE_COMMENT, DELETE_POST, SHOW_ERROR, SHOW_POST, GET_POSTS, SHOW_LOADING, GET_POST, CLEAR_POST, UPDATE_POST, CLEAR_ERRORS
}